### ISSUE TITLE
Securing the instance from data leakage

### ISSUE THREAD

**Issue by FeryET** [vinbigdata-medical/vindr-lab-deployment#11]
Hi.

I have succesfully deployed VinDr Lab in a staging environment for our laboratory, and right now I want to see how can I make sure the data we import in the software is secure and not accessible without having the right credentials. I have some questions to ask:

1. Is removing `/dicomweb` from nginx configuration a good approach? This enables external access to orthanc.
2. Apparently Orthanc is not secure and does not uses any authentication in the original docker-compose file. Is there anything I can do to make it more secure? Is this approach needed at all?
3. Can I couple keycloak with NGINX authentication?
4. Can I stop exposing minio and elastic search using NGINX?

Thanks!

**Comment by iamatsundere** [comment]
Hi, thanks for contributing for our product. 
1. No, because our viewer needs to access some APIs from Orthanc behind `/dicomweb`.
2. Because it's an OSS project, so we have to remove some parts to make our project clear and as-easy-as-possible to deploy. The closed project that we are using an middleware that stand between the NGINX and Orthanc, and connect to Keycloak to authorize the request (by bearer token and API key), only allow some essential request from the public call.
3. Yes, we did it with an middleware, there are some other ways to do that.
4. Yes, it is for debugging so we open them, you can close it.
