### ISSUE TITLE
Minio dashboard unavailable?

### ISSUE THREAD

**Issue by Rubenkl** [vinbigdata-medical/vindr-lab-deployment#8]
Hello!

I have tried configuring both using docker-compose and kubernetes, but using both methods I am not able to finalize the setup by visiting the Minio admin panel. After visiting http://localhost:8080/minio, I get redirected to http://localhost:40655, and results in a 'ERR_CONNECTION_TIMED_OUT'. 

Minio pod logs:
```
WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
         Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
API: http://10.42.0.32:9000  http://127.0.0.1:9000

Console: http://10.42.0.32:40655 http://127.0.0.1:40655

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (40655), please use --console-address ":PORT" to choose a static port.

```

Any idea what I am doing wrong?

**Comment by iamatsundere** [comment]
Hi @Rubenkl, sorry for the late reply. This issue came from the confliction with the latest version of MinIO and my config from previous deployment. I've made [a new commit](https://github.com/vinbigdata-medical/vindr-lab-deployment/releases/tag/v1.0.1), which has a lot of improvements. Please check it out! Many thanks!

**Comment by FeryET** [comment]
The issue is still persistent. The problem is that minio does not accept subpaths for whatever reason behind an nginx configuration.

**Comment by iamatsundere** [comment]
I've resolved in issue https://github.com/vinbigdata-medical/vindr-lab-deployment/issues/10
